#!/bin/bash

alias ls="ls -Gal"

if [[ `thefuck --version 2>&1 /dev/null; echo $?` == '0' ]]; then
    eval "$(thefuck --alias)"
fi

## Section for git related commands

alias gau="git add -u"
alias gaa="git add -A"
alias gcm="git commit -m"
alias gcam="git commit -a -m"

alias gs="git status"
alias gl="git log"

alias gps="git push"
alias gpl="git pull"
alias gch="git checkout"
alias gbr="git checkout -b"

gitAllFunction(){
    git commit -a -m "$1"
    git push
}

alias gcamp=gitAllFunction

## Section for mistakenly typed commands

alias sl="sl -e"
alias cd..="cd .."

alias clr="clear"

alias refresh="source ~/.bashrc"

