#! /bin/bash
###
#   .bash_profile is run for login shells (and new Terminal.app windows on
#   Mac), whereas .bashrc is run any other time bash is invoked.
#
#   This does some login specific things (welcome, print other statistics,
#   etc), and the .bashrc will house the more general configurations.
###

function fortune_b {
  fortune -a | while read line; do
    echo -e "\t"$line
  done
}

echo -e "\nWelcome $(whoami)!\n"
[[ -f /usr/games/fortune ]] || [[ -f /usr/local/bin/fortune ]] && fortune_b && echo

if [[ -f ~/.bashrc ]]; then
    source ~/.bashrc
fi
