#! /bin/bash
# vim: set filetype=sh:

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
  # Linux
  alias ls="ls -alph --color=auto"
  alias open="xdg-open"
elif [[ "$OSTYPE" == "darwin"* ]]; then
  # Mac OSX
  alias ls="ls -Galph"
else
  echo "Unknown OSTYPE."
fi

if [[ `thefuck --version 2>&1 /dev/null; echo $?` == '0' ]]; then
    eval "$(thefuck --alias)"
fi

## Section for git related commands

alias gau="git add -u"
alias gaa="git add -A"
alias gcm="git commit -m"
alias gcam="git commit -a -m"

alias gs="git status"
alias gl="git log"

alias gps="git push"
alias gpl="git pull"
alias gch="git checkout"
alias gbr="git checkout -b"

gitAllFunction(){
    git commit -a -m "$1"
    git push
}

alias gcamp=gitAllFunction

## Section for mistakenly typed commands

alias sl="sl -e"
alias cd..="cd .."

alias clr="clear"

alias refresh="source ~/.bashrc"

## Section for fun functions.

swapFiles() {
  mv $1 $1.tmp
  mv $2 $1
  mv $1.tmp $2
}

alias swp=swapFiles

## tmux
alias tmux="tmux -2"
alias a="tmux attach"
